version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - db  
  db:
     restart: always
     image: mongo:3.6
     ports:
       - "127.0.0.1:27017:27017"
     volumes:
       - /opt_docker/data/mongodb0:/data/db
       - /opt_docker/log/mongodb0:/log
  
